### PR TITLE
Convert the CARTA ICD to a reST document maintained in this repository

### PR DESCRIPTION
**Pull request by confluence**
This PR adds an initial converted version of the ICD, together with the conversion code (to be removed in a follow-up PR) and code for generating documentation automatically from the protocol buffer files (using an external tool and a Python script). The process for maintaining this documentation is described in the README.

Some details about our customisations:

* We define a custom ~~`:carta:`~~ `:carta:ref:` role which can be used instead of the more standard `:ref:` role to create internal references to CARTA messages and enums using either the `CamelCaseName` or the `SNAKE_CASE_NAME`.
* The protocol buffer document generation script colours some messages blue (frontend to backend) or red (backend to frontend) using various heuristics like the parent directory of the file and the name of the message. It's impossible to distinguish arbitrarily named stream messages from submessages, so please consistently put submessages in `defs.proto`, even if they're only used in one file.
* We use the plantweb extension to render plantuml diagrams as svg instead of embedding them as images. So you can edit the diagrams directly in the reST.

Further modifications can be made to the document at a later stage. Some known issues:

* ReadTheDocs has not yet been set up -- I thought that I could test it on a feature branch, but I'm not sure if that's actually possible. In the meantime, you can look at the docs locally by installing and running Sphinx. It's a good idea to do this anyway before committing changes.
* ~~The changelog should be converted to some kind of list. This is a small cosmetic change which can be done manually.~~
* ~~Nested inline markup is not allowed in reST, which means that internal references can't be preformatted or coloured, and coloured text can't be preformatted. This is surprisingly difficult to work around (without sacrificing legibility), but I think it's technically possible, and I will continue looking into it.~~
* Some of the protocol buffer messages aren't documented properly -- this needs to be changed in the code. Some of the existing comments should also be tweaked so that they don't render oddly in the document.

### CODE REVIEW

**Comment by veggiesaurus** [comment]
need to add `master_doc = 'index'` to the config

**Comment by confluence** [comment]
> need to add `master_doc = 'index'` to the config

`index` is the default since Sphinx 2.0 -- I'm not sure if we should support older versions.

**Comment by veggiesaurus** [comment]
> > need to add `master_doc = 'index'` to the config
> 
> `index` is the default since Sphinx 2.0 -- I'm not sure if we should support older versions.

good point. 

I think we should let this simmer for a while and get more people to look at it during the beta period. It's going to require a bit of a workflow change, so we should discuss it at our next meeting. 

It's going to make our life so much easier though :+1:

**Comment by confluence** [comment]
I'm happy to wait a bit before merging; I want to rewrite the reference extension the correct way rather than the lazy way, which should make it possible to style the links.

**Comment by confluence** [comment]
Update: I have rewritten the extension and extended the reference roles. We can now use the following custom roles:

* `:carta:ref:` -- a reference to a CARTA object, preformatted text, default link colour
* `:carta:f2b:` -- a reference to a CARTA object, preformatted text, blue
* `:carta:b2f:` -- a reference to a CARTA object, preformatted text, red
* `:carta:sub:` -- a reference to a CARTA object, preformatted text, black

The additional roles are purely cosmetic; they behave identically, but style the HTML element differently. This is a workaround to reST's inline style limitations (nesting of roles is not allowed).

**Comment by confluence** [comment]
I have made the coloured references smarter and simpler to use. There are now only two reference roles: `:carta:ref:`, which does not apply a text colour, and `:carta:refc:`, which automatically applies the correct text colour.

In addition to this, there are three custom interpreted text roles, which I didn't mention previously: `:f2b:`, `:b2f:` and `:comment:` (for the orange comment text). These only apply a colour to text. They can't be nested with other kinds of formatting, but it's very easy to add more roles like this if necessary.

**Comment by kswang1029** [comment]
@confluence Got the doc compiled! This looks great. 
Not sure if this is already mentioned somewhere, we need (or just me)
`pip install plantweb`
`pip install sphinxcontrib-svg2pdfconverter`

Also there are some warnings (not sure if it is important or not)

> (base) oxide:docs kswang$ make html
Running Sphinx v2.2.0
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 23 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
preparing documents... done
writing output... [100%] user_preferences                                                                            
WARNING: RSVG converter command 'rsvg-convert' cannot be run. Check the rsvg_converter_bin setting
WARNING: RSVG converter command 'rsvg-convert' cannot be run. Check the rsvg_converter_bin setting
WARNING: RSVG converter command 'rsvg-convert' cannot be run. Check the rsvg_converter_bin setting
WARNING: RSVG converter command 'rsvg-convert' cannot be run. Check the rsvg_converter_bin setting
WARNING: RSVG converter command 'rsvg-convert' cannot be run. Check the rsvg_converter_bin setting
WARNING: RSVG converter command 'rsvg-convert' cannot be run. Check the rsvg_converter_bin setting
WARNING: RSVG converter command 'rsvg-convert' cannot be run. Check the rsvg_converter_bin setting
generating indices...  genindexdone
writing additional pages...  searchdone
copying images... [  3%] ../_build/html/_images/plantweb/57562515cf1ce59812816b31a9652e67ba0d6d7f52e2cee42e4232de3aa1


For the message table, we need a slightly wider table to show things properly. (e.g. **compression_-type**, **La-bel**, **re-peated**)
Screen Shot 2020-08-20 at 10 18 03 AM


I tried to use other built-in themes such as classic or bizstyle (user manual uses this) and it helps.
classic
Screen Shot 2020-08-20 at 10 32 09 AM
bizstyle
Screen Shot 2020-08-20 at 10 32 18 AM

**Comment by confluence** [comment]
The dependencies are mentioned in the README -- I didn't include full commands because for some people it may be `pip3`.

What the table column widths should be depends on the theme -- I'll see if I can test the default Read The Docs theme locally.

**Comment by kswang1029** [comment]
line 51 of https://github.com/CARTAvis/carta-protobuf/blob/confluence/markdown-icd/docs/src/conf.py

**Comment by confluence** [comment]
@kswang1029 I actually couldn't reproduce your issue in the current theme at all, in Firefox or Chromium on Ubuntu: the table width remains constant no matter what the window size is, because the whole page is in a fixed-width element, and none of my table headers or contents are ever hyphenated. I think that this is some kind of CSS issue; possibly a side effect of the width set on the table. 

Everything I've found online so far seems to be trying to solve the opposite problem (adding word breaks) -- apparently Sphinx does this by default so that tables can display very long one-word symbol names, and the Read The Docs theme actually breaks this (I haven't tested it yet).

I did notice that the changelog table columns are too narrow in the PDF, so I will definitely change those. I have also changed the message columns slightly -- does that solve the issue?

Otherwise, what browser and OS are you using? If you inspect the CSS of the tables, does it make any difference if you remove the `width: 100%` from `table.proto` in the inspector?

**Comment by confluence** [comment]
> WARNING: RSVG converter command 'rsvg-convert' cannot be run. Check the rsvg_converter_bin setting

This is expected if you don't have this library installed. It shouldn't matter if you're not generating a PDF -- the HTML document uses the original SVG files. If you can see the images, then everything is OK.

**Comment by veggiesaurus** [comment]
> @kswang1029 I actually couldn't reproduce your issue in the current theme at all, in Firefox or Chromium on Ubuntu: the table width remains constant no matter what the window size is, because the whole page is in a fixed-width element, and none of my table headers or contents are ever hyphenated. I think that this is some kind of CSS issue; possibly a side effect of the width set on the table.

Could it be related to the device pixel ratio?

**Comment by confluence** [comment]
> Could it be related to the device pixel ratio?

It could, actually. I will test it on my non-hidpi laptop.

**Comment by confluence** [comment]
There doesn't appear to be any difference on a non-hidpi display.

@kswang, another thing you could try to do is manually change the column widths and see at what point the text stops breaking for you (they're set in the css of the `col` elements in the `colgroup` of each `table`, and they should add up to 100%). But first please check if the latest commit is OK.

**Comment by kswang1029** [comment]
@confluence With the latest commit, the table looks better. I checked with non-retina iMac with Safari and Chrome and see same (better) results. The only issue is the Field column might be too narrow for long field names thus the readability is not that ideal, but this is probably okay.

**Review by veggiesaurus — APPROVED** [review]

**Pull request merged**
